title: Stardroid 
description: A Custom Andriod ROM
theme: just-the-docs

url: https://noah-dev-codes.github.io/StarDroidDocs/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://noah-dev-codes.github.io/StarDroidDocs/
